spring:
  thymeleaf:
    cache: true

  freemarker:
    cache: false

  application:
    name: dbook

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/dbook}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        use_sql_comments: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1

jwt:
  secret: ${JWT_SECRET_KEY}
  access-token-expiration: 1800000

book:
  api:
    key: ${BOOK_API_KEY}

payment:
  toss:
    client-key: ${TOSS_PAYMENT_CLIENT_KEY}
    secret-key: ${TOSS_PAYMENT_SECRET_KEY}


library:
  default-code: "141553"
  base-url: "http://data4library.kr/api/"

logging:
  level:
    org:
      springframework:
        security: DEBUG

server:
  error:
    include-message: always
    include-stacktrace: always

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failureRateThreshold: 50


        waitDurationInOpenState: 10000ms
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true

    instances:
      bookApiCircuitBreaker:
        baseConfig: default


